version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - sqlite_data:/data
volumes:
  sqlite_data:
