version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://kanban:kanban@db:5432/kanban
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
